In [1]:
from stochastic_round.stochastic_ops import copy_stochastic_cuda_, copy_stochastic_
from stochastic_round.stochastic_ops import add_stochastic_cuda_, add_stochastic_
from stochastic_round.stochastic_ops import mul_stochastic_cuda_, mul_stochastic_
from stochastic_round.stochastic_ops import div_stochastic_cuda_, div_stochastic_
from stochastic_round.stochastic_ops import lerp_stochastic_cuda_, lerp_stochastic_
from stochastic_round.stochastic_ops import addcmul_stochastic_cuda_, addcmul_stochastic_
from stochastic_round.stochastic_ops import addcdiv_stochastic_cuda_, addcdiv_stochastic_
import torch

In [2]:
dim = 1024
source = torch.randn(dim, dim, dtype=torch.float32, device='cuda')
target_cuda = torch.randn(dim, dim, dtype=torch.bfloat16, device='cuda')
target_reg = target_cuda.clone()

copy_stochastic_cuda_(target_cuda, source)
copy_stochastic_(target_reg, source)
print(target_cuda - target_reg)



tensor([[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        ...,
        [ 0.0000,  0.0000,  0.0000,  ..., -0.0020,  0.0005,  0.0000],
        [ 0.0039,  0.0000,  0.0000,  ...,  0.0039,  0.0000,  0.0005],
        [ 0.0000,  0.0000,  0.0000,  ..., -0.0078,  0.0000,  0.0000]],
       device='cuda:0', dtype=torch.bfloat16)


In [3]:
dim = 1024
source = torch.randn(dim, dim, dtype=torch.float32, device='cuda')
target_cuda = torch.randn(dim, dim, dtype=torch.bfloat16, device='cuda')
target_reg = target_cuda.clone()

add_stochastic_cuda_(target_cuda, source)
add_stochastic_(target_reg, source)
print(target_cuda - target_reg)

tensor([[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        ...,
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0039, 0.0002, 0.0000],
        [0.0000, 0.0000, 0.0078,  ..., 0.0000, 0.0000, 0.0000]],
       device='cuda:0', dtype=torch.bfloat16)


In [4]:
dim = 1024
source = torch.randn(dim, dim, dtype=torch.float32, device='cuda')
target_cuda = torch.randn(dim, dim, dtype=torch.bfloat16, device='cuda')
target_reg = target_cuda.clone()

mul_stochastic_cuda_(target_cuda, source)
mul_stochastic_(target_reg, source)
print(target_cuda - target_reg)

tensor([[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        ...,
        [ 0.0000,  0.0000, -0.0010,  ..., -0.0156,  0.0078,  0.0000],
        [ 0.0000, -0.0078,  0.0000,  ...,  0.0000, -0.0078,  0.0000],
        [ 0.0000,  0.0000, -0.0020,  ...,  0.0000,  0.0000,  0.0000]],
       device='cuda:0', dtype=torch.bfloat16)


In [5]:
dim = 1024
source = torch.randn(dim, dim, dtype=torch.float32, device='cuda')
target_cuda = torch.randn(dim, dim, dtype=torch.bfloat16, device='cuda')
target_reg = target_cuda.clone()

div_stochastic_cuda_(target_cuda, source)
div_stochastic_(target_reg, source)
print(target_cuda - target_reg)


tensor([[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        ...,
        [ 0.0000,  0.0000, -0.0039,  ...,  0.0000,  0.0000,  0.0010],
        [-0.0039,  0.0000, -0.0039,  ...,  0.0000,  0.0078,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],
       device='cuda:0', dtype=torch.bfloat16)


In [6]:
dim = 1024
source = torch.randn(dim, dim, dtype=torch.float32, device='cuda')
target_cuda = torch.randn(dim, dim, dtype=torch.bfloat16, device='cuda')
target_reg = target_cuda.clone()

lerp_stochastic_cuda_(target_cuda, source, 0.5)
lerp_stochastic_(target_reg, source, 0.5)
print(target_cuda - target_reg)

tensor([[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        ...,
        [ 0.0000,  0.0000, -0.0039,  ...,  0.0000,  0.0039,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0039,  0.0000],
        [ 0.0000,  0.0000, -0.0039,  ...,  0.0000,  0.0000,  0.0078]],
       device='cuda:0', dtype=torch.bfloat16)


In [7]:
dim = 1024
tensor1 = torch.randn(dim, dim, dtype=torch.float32, device='cuda')
tensor2 = torch.randn(dim, dim, dtype=torch.float32, device='cuda')
target_cuda = torch.randn(dim, dim, dtype=torch.bfloat16, device='cuda')
target_reg = target_cuda.clone()

addcmul_stochastic_cuda_(target_cuda, tensor1, tensor2, 0.5)
addcmul_stochastic_(target_reg, tensor1, tensor2, 0.5)
print(target_cuda - target_reg)


tensor([[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        ...,
        [ 0.0000,  0.0000, -0.0078,  ...,  0.0039, -0.0078,  0.0078],
        [ 0.0000,  0.0000,  0.0078,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000, -0.0020,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],
       device='cuda:0', dtype=torch.bfloat16)


In [8]:
dim = 1024
tensor1 = torch.randn(dim, dim, dtype=torch.float32, device='cuda')
tensor2 = torch.randn(dim, dim, dtype=torch.float32, device='cuda')
target_cuda = torch.randn(dim, dim, dtype=torch.bfloat16, device='cuda')
target_reg = target_cuda.clone()

addcdiv_stochastic_cuda_(target_cuda, tensor1, tensor2, 0.5)
addcdiv_stochastic_(target_reg, tensor1, tensor2, 0.5)
print(target_cuda - target_reg)

tensor([[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        ...,
        [ 0.0000, -0.0039, -0.0078,  ...,  0.0000,  0.0039,  0.0156],
        [ 0.0005,  0.0000,  0.0000,  ...,  0.0000,  0.0000, -0.0156],
        [ 0.0000,  0.0000,  0.0039,  ...,  0.0000,  0.0000,  0.0000]],
       device='cuda:0', dtype=torch.bfloat16)
